### ISSUE TITLE
Some extensions cause issues/don't load at all

### ISSUE THREAD

**Issue by derpygamer2142** [EurekaScratch/eureka#1]
![image](https://github.com/SimonShiki/chibi/assets/93667155/00296c24-3970-46b6-9822-f3e8bbbd9a31)
![image](https://github.com/SimonShiki/chibi/assets/93667155/4ad8ce1c-f251-43e2-b424-73c10cdf1513)
The HTTP extensions is very buggy.
Not sure if the above are due to scratch blocking it somehow.

**Comment by SimonShiki** [comment]
Some extensions rely on content unique to TurboWarp, and this extension uses BitmapSkin exposed by TurboWarp. Unfortunately, this cannot be solved via external scripting, Because normal Scratch does not expose them, and class functions cannot be obtained from existing instances.

**Comment by SimonShiki** [comment]
But I guess HTTP usage of ``Scratch.fetch`` can be solved and I will add TurboWarp extension compatibility if possible in the future

**Comment by derpygamer2142** [comment]
got it

**Comment by SimonShiki** [comment]
Now HTTP extension should work properly.

**Comment by derpygamer2142** [comment]
very cool
