### ISSUE TITLE
Support for operation spork

### ISSUE THREAD

**Issue by yuri-kiss** [EurekaScratch/eureka#106]
This uses modern blockly and is codenamed "spork" by the google engineers and scratch: https://gonfunko.github.io/scratch-gui/

**Comment by SimonShiki** [comment]
Part of #54

**Comment by yuri-kiss** [comment]
> Part of #54

epic

**Comment by SimonShiki** [comment]
The refactored version of eureka has ready for the first release: https://github.com/EurekaScratch/eureka/releases
The refactored version of Eureka adds a built-in dashboard modal and support for new scratch blocks, which should theoretically work on any platform except Codingclip
![image](https://github.com/user-attachments/assets/0ddcb8a3-84e1-4fbd-9ed1-0785a0728edd)

**Comment by yuri-kiss** [comment]
Nice
