### ISSUE TITLE
Does loading extension from url actually works?

### ISSUE THREAD

**Issue by The11thPencil** [EurekaScratch/eureka#11]
![image](https://github.com/EurekaScratch/eureka-loader/assets/124476952/a5424544-62ca-4375-9040-62f95f80ec1c)

I tried loading with frontend and it also doesnt work. In the console it only says "handshake with frontend". No errors given

**Comment by SimonShiki** [comment]
1. CCW format extension is not supported by Eureka. The only Eureka accepted is standard Scratch Extension.
2. For extensions running in the sandbox, the mimetype of the URL must be ``text/javascript``. Unsandboxes do not have this restriction. I don't know if CCW has restrictions on this, but you might as well try it in non-sandbox mode?
