### ISSUE TITLE
ReduxStore export

### ISSUE THREAD

**Issue by yuri-kiss** [EurekaScratch/eureka#117]
I don't know how difficult this is but it would be nice if Eureka could expose ReduxStore to extensions.
On TurboWarp this is already possible using `window.ReduxStore` and checking if the project is packaged.
Personally I have used this many times to force updates into the GUI and get the theme value.

**Comment by SimonShiki** [comment]
This feature is already supported in Charlotte and I will port it to Eureka later.

**Comment by yuri-kiss** [comment]
> This feature is already supported in Charlotte and I will port it to Eureka later.

kk!

**Comment by SimonShiki** [comment]
Basically implemented in commit 4c40419

Notes: If you need global ReduxStore instance, turn Trap->ReduxStore and Behavior->PolyfillGlobalInstances on.
