### ISSUE TITLE
在ccw.site 由于更新 已无法使用

### ISSUE THREAD

**Issue by skydog221** [EurekaScratch/eureka#131]
如题，由于ccw的更新，eureka已经无法获取vm，只能返回undefined
![QQ_1732431124422](https://github.com/user-attachments/assets/c7b1e8ad-c559-4caa-b5ff-d068ca78d32d)
希望可以修复或给出解决办法！
感谢！

**Comment by SimonShiki** [comment]
Eureka Aurora 构建经测试无使用问题
![image](https://github.com/user-attachments/assets/b8ba9094-7187-49fe-bd8e-19b255d7df32)

**Comment by skydog221** [comment]
> Eureka Aurora 构建经测试无使用问题 ![图像](https://private-user-images.githubusercontent.com/59327348/389273134-b8ba9094-7187-49fe-bd8e-19b255d7df32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MzgzMTUsIm5iZiI6MTczMjUzODAxNSwicGF0aCI6Ii81OTMyNzM0OC8zODkyNzMxMzQtYjhiYTkwOTQtNzE4Ny00OWZlLWJkOGUtMTliMjU1ZDdkZjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDEyMzMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NDhiZjBlMGE5YzkwM2Y4ZjU4NjFmZjc3OTRhMmRlNGU2MDk1N2QxYzkwOWY2YzhhMjk1Y2Q3Mzg0NjdiOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WEWtn1opEvzViK9uVuFFjf0vN4CfZ4yMkkze2wgA0VA)

你好！
首先感谢您的关注
但这边依旧有问题呢
![QQ_1732538079314](https://github.com/user-attachments/assets/450432d5-b582-4958-a166-e44427ff51cc)
需要尝试获取vm（即eureka.vm）
可以正常加载，但获取到的vm处于udf状态

**Comment by SimonShiki** [comment]
请附带详细运行环境（系统/浏览器版本），可复现作品页面以及完整复现流程，并提供浏览器控制台日志

**Comment by skydog221** [comment]
> 请附带详细运行环境（系统/浏览器版本），可复现作品页面以及完整复现流程，并提供浏览器控制台日志
感谢您的关注！下面是我的信息：
# 系统&浏览器信息
Windows 11 专业工作站版
24H2
26120.1340
浏览器：Edge 132.0.2957.11 (正式版本) stable应用，beta频道 (64 位)
搭载油猴5.3.6216
本机任意作品可复现，如https://www.ccw.site/detail/669e5988e1534b396b2c202e
# 复现流程:
1. 打开上述任意ccw作品网址
2. 待工程加载完毕（即出现“开始运行”字样）
3. 浏览器控制台输入eureka.vm（有eureka提示，说明eureka已成功注入并写入window）
4. 返回图中内容
# 完整日志&剥离的有效日志
浏览器完整日志（剥离出的针对此issue有效日志见下）（有关于runtime的warning，证明vm存在但无法获取）:
<details>

2res.wx.qq.com/connect/zh_CN/htmledition/js/wxLogin.js:1




Microsoft Edge is moving towards a new experience that allows users to choose to browse without third-party cookies.
2res.wx.qq.com/open/js/jweixin-1.6.0.js:1




Microsoft Edge is moving towards a new experience that allows users to choose to browse without third-party cookies.
7[Deprecation]-ms-high-constrast is in the process of being deprecated. Please see for tips on updating to the new Forced Colors Mode standard.
vendor~main.58c21341.js:2 [MAGOTAN WARNING] 在公众号场景下，未正确设置 account 会导致关联的用户信息不一致，请正确配置 Magotan

21[Deprecation]-ms-high-contrast-adjust is in the process of being deprecated. Please see for tips on updating to the new Forced Colors Mode standard.
vendor~main.58c21341.js:2 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently

vendor~main.58c21341.js:2 💡 Eureka eureka-loader 8.1
vendor~main.58c21341.js:2 💡 Eureka Listening bind function...
content.js:202 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
vendor~main.58c21341.js:2 onResize viewport 640 360
vendor~main.58c21341.js:172 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.

vendor~main.58c21341.js:2 [Violation]Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

vendor~main.58c21341.js:2 💡 Eureka Cannot find vm instance, stop listening.
vendor~main.58c21341.js:2 💡 Eureka Cannot find vm in this page, stop injecting.
vendor~main.58c21341.js:2 [Violation]'requestAnimationFrame' handler took 141ms
vendor~main.58c21341.js:172 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently

vendor~main.58c21341.js:2 Translation for "witCat.dollyPro.tooltip.control_delete_this_clone" in "zh-cn" is missing

vendor~main.58c21341.js:2 Translation for "witCat.dollyPro.tooltip.control_start_as_clone" in "zh-cn" is missing

vendor~main.58c21341.js:2 Translation for "witCat.dollyPro.tooltip.undefined" in "zh-cn" is missing

vendor~main.58c21341.js:2 [Violation]'setTimeout' handler took 169ms
vendor~main.58c21341.js:2 [Violation]'requestAnimationFrame' handler took 250ms
vendor~main.58c21341.js:2 You are using unsupported APIs. WHEN your code breaks, do not expect help.

i_will_not_ask_for_help_when_these_break @ vendor~main.58c21341.js:172


</details>


Eureka message：
```
💡 Eureka eureka-loader 8.1
💡 Eureka Listening bind function...
💡 Eureka Cannot find vm instance, stop listening.
💡 Eureka Cannot find vm in this page, stop injecting.
```

**Comment by SimonShiki** [comment]
1. 看起来您仍在使用旧版 Eureka，并且 Eureka 的执行时机过晚。Eureka 自 11 开始提供了在页面加载后仍完成注入的操作，并修复了部分加载问题。请升级到最新版本 Eureka 并删除旧版 Eureka 后再试。
2. 如果您不想升级的话，可以尝试在油猴中尝试找到类似“同步界面”的选项并打开，他会强制在 Eureka 完全加载完毕后再加载界面（不推荐，新版已有更优方案）

**Comment by skydog221** [comment]
> 1. 看起来您仍在使用旧版 Eureka，并且 Eureka 的执行时机过晚。Eureka 自 11 开始提供了在页面加载后仍完成注入的操作，并修复了部分加载问题。请升级到最新版本 Eureka 并删除旧版 Eureka 后再试。
> 2. 如果您不想升级的话，可以尝试在油猴中尝试找到类似“同步界面”的选项并打开，他会强制在 Eureka 完全加载完毕后再加载界面（不推荐，新版已有更优方案）

谢谢呢~更新后确实可以了呢！
是否能在脚本中添加自动更新的元数据呢？

**Comment by SimonShiki** [comment]
> > 1. 看起来您仍在使用旧版 Eureka，并且 Eureka 的执行时机过晚。Eureka 自 11 开始提供了在页面加载后仍完成注入的操作，并修复了部分加载问题。请升级到最新版本 Eureka 并删除旧版 Eureka 后再试。
> > 2. 如果您不想升级的话，可以尝试在油猴中尝试找到类似 “同步界面” 的选项并打开，他会强制在 Eureka 完全加载完毕后再加载界面（不推荐，新版已有更优方案）
> 
> 谢谢呢～更新后确实可以了呢！ 是否能在脚本中添加自动更新的元数据呢？

会优先考虑的
