### ISSUE TITLE
不支持gandi特殊格式的拓展

### ISSUE THREAD

**Issue by skydog221** [EurekaScratch/eureka#39]
ccw.site 共创世界
使用gandi编辑器 特殊格式的拓展（由window.tempExt注册拓展）不加载
测试拓展的链接：
[cdn.jsdelivr.net/gh/MoreBugOfDog/custom-extension@informality/experience/hacker/ThreeJS_Scratch.js](https://cdn.jsdelivr.net/gh/MoreBugOfDog/custom-extension@informality/experience/hacker/ThreeJS_Scratch.js)
国内服务器备用链接：
https://static.codemao.cn/coco/player/unstable/Sye6ljBRT.text/javascript?hash=Fh6iAoSxjdRuLjEi5mJ4QDjWH8vV

**Comment by SimonShiki** [comment]
Gandi格式的扩展加载目前不在Eureka的开发计划内。
