### ISSUE TITLE
Support ElectraMod (yet another PenguinMod mod)

### ISSUE THREAD

**Issue by Aness6040** [EurekaScratch/eureka#47]
U can check here
https://electramod.vercel.app/editor.html

**Comment by FurryR** [comment]
It will be available in future releases.

**Comment by Aness6040** [comment]
> It will be available in future releases.

It's already available (built-in)

It's just not added to the list

**Comment by FurryR** [comment]
Eureka supports every modern Scratch platform in theory. Seems like that you modified userscript's metadata, adding ElectraMod into the included websites, and that's what I'm talking about.
ElectraMod will be supported (adding to the supported websites officially) in future releases, but it might take some time to do so.

**Comment by Aness6040** [comment]
> Eureka supports every modern Scratch platform in theory. Seems like that you modified userscript's metadata, adding ElectraMod into the included websites, and that's what I'm talking about. ElectraMod will be supported (adding to the supported websites officially) in future releases, but it might take some time to do so.

Now I understand

**Comment by SimonShiki** [comment]
done in #55
