### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by SimonShiki** [EurekaScratch/eureka#54]
Branch: https://github.com/EurekaScratch/eureka/tree/refactor
# Proposed Changes
- [x] Migrate from Webpack to Rollup
- [x] New trap method from Charlotte
- [ ] Native Charlotte Addon Support
- [x] Code quality improvements
- [x] Add modern blockly support
- [x] Built-in dashboard

**Comment by FurryR** [comment]
tsup yea
