### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by kokofixcomputers** [EurekaScratch/eureka#62]
May i ask how to compile the src into the js or the extension? i have a method that used to work this morning but wouldn't work now: node scripts/generate-extension.js

**Comment by SimonShiki** [comment]
run ``yarn build`` or ``npm build`` if you use npm. then you can run ``yarn extension:pack`` to pack browser extension.

**Comment by kokofixcomputers** [comment]
thanks what about just npm?

**Comment by kokofixcomputers** [comment]
can i use npm extension:pack?

**Comment by SimonShiki** [comment]
> can i use npm extension:pack?

sure

**Comment by kokofixcomputers** [comment]
> > can i use npm extension:pack?
> 
> sure

thanks so much!

**Comment by kokofixcomputers** [comment]
> run `yarn build` or `npm build` if you use npm. then you can run `yarn extension:pack` to pack browser extension.

npm build 

Unknown command: "build"

Did you mean this?
    npm run build # run the "build" package script

To see a list of supported npm commands, run:
  npm help

**Comment by kokofixcomputers** [comment]
oh it's run build
